SpaceLSCustom = {
    jobsRights = {["mechanic"] = true},
    coordsOpenMenu = {
        vector3(937.533, -970.853, 38.975)
    }
}

SpaceLSCustom.Klaxon = {
    ["Standard"] = {
        ["Klaxon Défault"] = {
            price = 0,
            modIndex = -1
        },
    },

}

SpaceLSCustom.Category = {
    {
        id = 0,
        name = "Compacts",
        multiplier = {
            blindage = 1,
            freins = 3,
            moteur = 5,
            suspension = 8,
            transmission = 10,
            frontWheelsBikeMenu = 5,
            eclairage = 8,
            phare = 5,
            neon = 12,
            neonColor = 10,
            wheels = 10,
            modAerials = 3,
            customTire = 10,
            maskPhares = 5,
            doorsLeft = 5,
            windowTint = 5,
            modTank = 2,
            interiorColor = 13,
            livery = 8,
            doorsRight = 5,
            modEngineBay = 8,
            modEngineBay2 = 8,
            dashboardColor = 14,
            Spoiler = 14,
            frontBumper = 5,
            roofAir = 5,
            backBumper = 5,
            sideSkirt = 5,
            carExhaust = 5,
            carFrame = 5,
            modHydrolic = 5,
            carGrille = 5,
            figurines = 2,
            trunkMod = 5,
            carHood = 5,
            carFender = 5,
            carRetro = 5,
            carRoof = 5,
            carSubwoofer = 8,
            carExterior = 8,
            dashbordDetails = 8,
            jauges = 5,
            speakersdoor = 10,
            visualSeats = 10,
            modSpeaker = 5,
            steeringWheel = 10,
            ShiftLever = 10
        }
    },
    {
        id = 1,
        name = "Sedans",
        multiplier = {
            blindage = 1,
            freins = 3,
            moteur = 5,
            suspension = 8,
            transmission = 10,
            maskPhares = 5,
            eclairage = 8,
            phare = 5,
            neon = 12,
            roofAir = 5,
            neonColor = 10,
            doorsRight = 5,
            doorsLeft = 5,
            wheels = 10,
            modTank = 2,
            modSpeaker = 5,
            livery = 8,
            trunkMod = 5,
            modAerials = 3,
            frontWheelsBikeMenu = 5,
            customTire = 10,
            windowTint = 5,
            modEngineBay = 8,
            modEngineBay2 = 8,
            interiorColor = 13,
            dashboardColor = 14,
            Spoiler = 14,
            frontBumper = 5,
            modHydrolic = 5,
            backBumper = 5,
            sideSkirt = 5,
            carExhaust = 5,
            carFrame = 5,
            carGrille = 5,
            carHood = 5,
            carFender = 5,
            carRetro = 5,
            carRoof = 5,
            carSubwoofer = 8,
            carExterior = 8,
            dashbordDetails = 8,
            figurines = 2,
            jauges = 5,
            speakersdoor = 10,
            visualSeats = 10,
            steeringWheel = 10,
            ShiftLever = 10
        }
    },
    {
        id = 2,
        name = 'SUVS',
        multiplier = {
            blindage = 1,
            freins = 3,
            moteur = 5,
            suspension = 8,
            transmission = 10,
            eclairage = 8,
            phare = 5,
            doorsLeft = 5,
            modEngineBay = 8,
            modEngineBay2 = 8,
            modHydrolic = 5,
            modTank = 2,
            neon = 12,
            neonColor = 10,
            livery = 8,
            doorsRight = 5,
            trunkMod = 5,
            maskPhares = 5,
            wheels = 10,
            customTire = 10,
            modSpeaker = 5,
            windowTint = 5,
            modAerials = 3,
            roofAir = 5,
            interiorColor = 13,
            dashboardColor = 14,
            Spoiler = 14,
            frontBumper = 5,
            frontWheelsBikeMenu = 5,
            backBumper = 5,
            sideSkirt = 5,
            carExhaust = 5,
            carFrame = 5,
            carGrille = 5,
            carHood = 5,
            carFender = 5,
            carRetro = 5,
            figurines = 2,
            carRoof = 5,
            carSubwoofer = 8,
            carExterior = 8,
            dashbordDetails = 8,
            jauges = 5,
            speakersdoor = 10,
            visualSeats = 10,
            steeringWheel = 10,
            ShiftLever = 10
        }
    },
    {
        id = 3,
        name = 'Coupes',
        multiplier = {
            blindage = 1,
            freins = 3,
            moteur = 5,
            suspension = 8,
            transmission = 10,
            eclairage = 8,
            phare = 5,
            neon = 12,
            neonColor = 10,
            wheels = 10,
            modAerials = 3,
            customTire = 10,
            livery = 8,
            windowTint = 5,
            modHydrolic = 5,
            modSpeaker = 5,
            roofAir = 5,
            trunkMod = 5,
            interiorColor = 13,
            dashboardColor = 14,
            doorsRight = 5,
            doorsLeft = 5,
            Spoiler = 14,
            frontWheelsBikeMenu = 5,
            modTank = 2,
            maskPhares = 5,
            frontBumper = 5,
            modEngineBay = 8,
            modEngineBay2 = 8,
            backBumper = 5,
            figurines = 2,
            sideSkirt = 5,
            carExhaust = 5,
            carFrame = 5,
            carGrille = 5,
            carHood = 5,
            carFender = 5,
            carRetro = 5,
            carRoof = 5,
            carSubwoofer = 8,
            carExterior = 8,
            dashbordDetails = 8,
            jauges = 5,
            speakersdoor = 10,
            visualSeats = 10,
            steeringWheel = 10,
            ShiftLever = 10
        }
    },
    {
        id = 4,
        name = 'Muscle',
        multiplier = {
            blindage = 1,
            freins = 3,
            moteur = 5,
            suspension = 8,
            transmission = 10,
            eclairage = 8,
            phare = 5,
            neon = 12,
            neonColor = 10,
            doorsRight = 5,
            roofAir = 5,
            modTank = 2,
            wheels = 10,
            modAerials = 3,
            customTire = 10,
            windowTint = 5,
            doorsLeft = 5,
            interiorColor = 13,
            modSpeaker = 5,
            modHydrolic = 5,
            trunkMod = 5,
            maskPhares = 5,
            livery = 8,
            dashboardColor = 14,
            Spoiler = 14,
            frontWheelsBikeMenu = 5,
            frontBumper = 5,
            backBumper = 5,
            sideSkirt = 5,
            carExhaust = 5,
            carFrame = 5,
            carGrille = 5,
            modEngineBay = 8,
            modEngineBay2 = 8,
            carHood = 5,
            carFender = 5,
            carRetro = 5,
            carRoof = 5,
            carSubwoofer = 8,
            carExterior = 8,
            dashbordDetails = 8,
            jauges = 5,
            speakersdoor = 10,
            visualSeats = 10,
            figurines = 2,
            steeringWheel = 10,
            ShiftLever = 10
        }
    },
    {
        id = 5,
        name = "Sports Classics",
        multiplier = {
            blindage = 1,
            freins = 3,
            moteur = 5,
            suspension = 8,
            transmission = 10,
            eclairage = 8,
            phare = 5,
            neon = 12,
            neonColor = 10,
            wheels = 10,
            roofAir = 5,
            modSpeaker = 5,
            maskPhares = 5,
            modTank = 2,
            customTire = 10,
            modEngineBay = 8,
            modEngineBay2 = 8,
            trunkMod = 5,
            doorsLeft = 5,
            livery = 8,
            windowTint = 5,
            modAerials = 3,
            doorsRight = 5,
            interiorColor = 13,
            dashboardColor = 14,
            Spoiler = 14,
            frontWheelsBikeMenu = 5,
            frontBumper = 5,
            backBumper = 5,
            sideSkirt = 5,
            carExhaust = 5,
            carFrame = 5,
            carGrille = 5,
            carHood = 5,
            carFender = 5,
            carRetro = 5,
            carRoof = 5,
            carSubwoofer = 8,
            figurines = 2,
            carExterior = 8,
            modHydrolic = 5,
            dashbordDetails = 8,
            jauges = 5,
            speakersdoor = 10,
            visualSeats = 10,
            steeringWheel = 10,
            ShiftLever = 10
        }
    },
    {
        id = 6,
        name = "Sports",
        multiplier = {
            blindage = 1,
            freins = 3,
            moteur = 5,
            suspension = 8,
            transmission = 10,
            eclairage = 8,
            phare = 5,
            neon = 12,
            neonColor = 10,
            trunkMod = 5,
            maskPhares = 5,
            wheels = 10,
            customTire = 10,
            livery = 8,
            windowTint = 5,
            interiorColor = 13,
            dashboardColor = 14,
            modEngineBay = 8,
            modEngineBay2 = 8,
            frontWheelsBikeMenu = 5,
            Spoiler = 14,
            modAerials = 3,
            roofAir = 5,
            frontBumper = 5,
            backBumper = 5,
            sideSkirt = 5,
            carExhaust = 5,
            doorsRight = 5,
            modTank = 2,
            carFrame = 5,
            doorsLeft = 5,
            carGrille = 5,
            carHood = 5,
            carFender = 5,
            carRetro = 5,
            carRoof = 5,
            carSubwoofer = 8,
            carExterior = 8,
            modSpeaker = 5,
            figurines = 2,
            modHydrolic = 5,
            dashbordDetails = 8,
            jauges = 5,
            speakersdoor = 10,
            visualSeats = 10,
            steeringWheel = 10,
            ShiftLever = 10
        }
    },
    {
        id = 7,
        name = "Super",
        multiplier = {
            blindage = 1,
            freins = 3,
            moteur = 5,
            suspension = 8,
            transmission = 10,
            roofAir = 5,
            eclairage = 8,
            phare = 5,
            neon = 12,
            neonColor = 10,
            livery = 8,
            wheels = 10,
            customTire = 10,
            maskPhares = 5,
            frontWheelsBikeMenu = 5,
            modEngineBay = 8,
            modEngineBay2 = 8,
            windowTint = 5,
            modAerials = 3,
            doorsRight = 5,
            interiorColor = 13,
            modTank = 2,
            dashboardColor = 14,
            Spoiler = 14,
            modHydrolic = 5,
            doorsLeft = 5,
            frontBumper = 5,
            backBumper = 5,
            sideSkirt = 5,
            carExhaust = 5,
            carFrame = 5,
            carGrille = 5,
            carHood = 5,
            carFender = 5,
            carRetro = 5,
            carRoof = 5,
            carSubwoofer = 8,
            carExterior = 8,
            trunkMod = 5,
            modSpeaker = 5,
            dashbordDetails = 8,
            jauges = 5,
            speakersdoor = 10,
            visualSeats = 10,
            figurines = 2,
            steeringWheel = 10,
            ShiftLever = 10
        }
    },
    {
        id = 8,
        name = "Motorcycles",
        multiplier = {
            blindage = 1,
            freins = 3,
            moteur = 5,
            suspension = 8,
            transmission = 10,
            eclairage = 8,
            phare = 5,
            neon = 12,
            neonColor = 10,
            modTank = 2,
            wheels = 10,
            customTire = 10,
            windowTint = 5,
            interiorColor = 13,
            doorsRight = 5,
            dashboardColor = 14,
            Spoiler = 14,
            maskPhares = 5,
            frontBumper = 5,
            modSpeaker = 5,
            frontWheelsBikeMenu = 5,
            backBumper = 5,
            doorsLeft = 5,
            livery = 8,
            modHydrolic = 5,
            modAerials = 3,
            sideSkirt = 5,
            carExhaust = 5,
            carFrame = 5,
            carGrille = 5,
            carHood = 5,
            carFender = 5,
            carRetro = 5,
            carRoof = 5,
            trunkMod = 5,
            figurines = 2,
            modEngineBay = 8,
            modEngineBay2 = 8,
            carSubwoofer = 8,
            carExterior = 8,
            roofAir = 5,
            dashbordDetails = 8,
            jauges = 5,
            speakersdoor = 10,
            visualSeats = 10,
            steeringWheel = 10,
            ShiftLever = 10
        }
    },
    {
        id = 9,
        name = "Off-road",
        multiplier = {
            blindage = 1,
            freins = 3,
            moteur = 5,
            suspension = 8,
            transmission = 10,
            eclairage = 8,
            phare = 5,
            neon = 12,
            doorsRight = 5,
            neonColor = 10,
            wheels = 10,
            modSpeaker = 5,
            customTire = 10,
            windowTint = 5,
            roofAir = 5,
            modTank = 2,
            livery = 8,
            maskPhares = 5,
            frontWheelsBikeMenu = 5,
            trunkMod = 5,
            doorsLeft = 5,
            modHydrolic = 5,
            interiorColor = 13,
            dashboardColor = 14,
            Spoiler = 14,
            frontBumper = 5,
            modAerials = 3,
            backBumper = 5,
            sideSkirt = 5,
            modEngineBay = 8,
            modEngineBay2 = 8,
            carExhaust = 5,
            carFrame = 5,
            carGrille = 5,
            carHood = 5,
            carFender = 5,
            carRetro = 5,
            carRoof = 5,
            carSubwoofer = 8,
            carExterior = 8,
            dashbordDetails = 8,
            jauges = 5,
            speakersdoor = 10,
            visualSeats = 10,
            steeringWheel = 10,
            ShiftLever = 10,
            figurines = 2
        },
    },
    {
        id = 10,
        name = "Industrial",
        multiplier = {
            blindage = 1,
            freins = 3,
            moteur = 5,
            suspension = 8,
            transmission = 10,
            eclairage = 8,
            phare = 5,
            neon = 12,
            frontWheelsBikeMenu = 5,
            neonColor = 10,
            wheels = 10,
            customTire = 10,
            livery = 8,
            modEngineBay = 8,
            modEngineBay2 = 8,
            modTank = 2,
            doorsLeft = 5,
            maskPhares = 5,
            modAerials = 3,
            windowTint = 5,
            doorsRight = 5,
            interiorColor = 13,
            dashboardColor = 14,
            Spoiler = 14,
            frontBumper = 5,
            backBumper = 5,
            roofAir = 5,
            sideSkirt = 5,
            carExhaust = 5,
            carFrame = 5,
            carGrille = 5,
            carHood = 5,
            modSpeaker = 5,
            carFender = 5,
            trunkMod = 5,
            carRetro = 5,
            carRoof = 5,
            carSubwoofer = 8,
            carExterior = 8,
            dashbordDetails = 8,
            jauges = 5,
            speakersdoor = 10,
            modHydrolic = 5,
            visualSeats = 10,
            steeringWheel = 10,
            figurines = 2,
            ShiftLever = 10
        }
    }
}

SpaceLSCustom.Turbo = {
    {
        name = "Aucun",
        modIndex = -1,
        enable = false,
        price = 0
    },
    {
        name = "Tuning Turbo",
        modIndex = 0,
        enable = 1,
        price = 125000
    }
}

SpaceLSCustom.Hydraulics = {
    {
        name = "Aucun",
        enable = false,
        price = 0
    },
    {
        name = "Hydraulique",
        enable = true,
        price = 5000, 
    }
}

SpaceLSCustom.Moteur = {
    {
        name = "Reprog moteur Niv.1",
        modIndex = 0,
        price = 9000,
        isVIP = false,
        requiredGrade = "none",
    },
    {
        name = "Reprog moteur Niv.2",
        modIndex = 1,
        price = 12500,
        isVIP = false,
        requiredGrade = "none",
    },
    {
        name = "Reprog moteur Niv.3",
        modIndex = 2,
        price = 18000,
        isVIP = false,
        requiredGrade = "none",
    },
    {
        name = "Reprog moteur Niv.4",
        modIndex = 3,
        price = 33500,
        isVIP = false,
        requiredGrade = "none"
    }
}

SpaceLSCustom.Freins = {
    {
        name = "Frein de série",
        modIndex = -1,
        price = 0,
        isVIP = false,
        requiredGrade = "none"
    },
    {
        name = "Frein de rue",
        modIndex = 0,
        price = 20000,
        isVIP = false,
        requiredGrade = "none"
    },
    {
        name = "Frein de sport",
        modIndex = 1,
        price = 27000,
        isVIP = false,
        requiredGrade = "none"
    },
    {
        name = "Frein de course",
        modIndex = 2,
        price = 35000,
        isVIP = false,
        requiredGrade = "none"
    }
}

--[[
    Todo : répertorier à la main tous les klaxons pour les trier comme dans gta:o
]]

SpaceLSCustom.Klaxon = {
    {
        name = "Klaxon par défault",
        modIndex = -1,
        price = 0,
        isVIP = false,
        requiredGrade = "none",
    }
}

for counter = 0, 56 do
    SpaceLSCustom.Klaxon[#SpaceLSCustom.Klaxon+1] = {
        name = "Klaxon " .. counter,
        modIndex = counter,
        price = (counter + 1) * 1000,
        isVIP = false,
        requiredGrade = "none",
    }
end

SpaceLSCustom.Eclairage = {
    Phares = {
        {
            name = "Phare de série",
            enableXenon = false,
            modIndex = -1,
            price = 0,
            isVIP = false,
            requiredGrade = "none",
        },
        {
            name = "Phares au xénon",
            enableXenon = true,
            modIndex = 3,
            price = 7500,
            isVIP = false,
            requiredGrade = "none",
        }
    },

    Neons = {
        {
            name = "Aucun",
            enableNeon = false,
            modIndex = {-1},
            price = 0,
            isVIP = false,
            requiredGrade = "none",
        },
        {
            name = "Avant, arrière et côtés",
            enableNeon = true,
            modIndex = {0, 1, 2, 3},
            price = 1500,
            isVIP = false,
            requiredGrade = "none",
        },

        Color = {
            {
                name = "Blanc",
                color = {222, 222, 255},
                price = 500,
            },
            {
                name = "Bleu",
                color = {2, 21, 255},
                price = 500,
            },
            {
                name = "Bleu électrique",
                color = {3, 83, 255},
                price = 500,
            },
            {
                name = "Vert Menthe",
                color = {0, 255, 140},
                price = 500,
            },
            {
                name = "Vert Lime",
                color = {94, 255, 1},
                price = 500,   
            },
            {
                name = "Jaune",
                color = {255, 255, 0},
                price = 500,
            }
        }
    }
}

SpaceLSCustom.Blindage = {
    {
        name = "Aucun",
        modIndex = -1,
        price = 0,
        isVIP = false,
        requiredGrade = "none",
    },
    {
        name = "Blindage amélioré de 20%",
        modIndex = 0,
        price = 1625,
        isVIP = false,
        requiredGrade = "none",
    },
    {
        name = "Blindage amélioré de 40%",
        modIndex = 1,
        price = 4062,
        isVIP = false,
        requiredGrade = "none",
    },
    {
        name = "Blindage amélioré de 60%",
        modIndex = 2,
        price = 1625,
        isVIP = false,
        requiredGrade = "none",
    },
    {
        name = "Blindage amélioré de 80%",
        modIndex = 3,
        price = 1625,
        isVIP = false,
        requiredGrade = "none",
    },
    {
        name = "Blindage amélioré de 100%",
        modIndex = 4,
        price = 1625,
        isVIP = false,
        requiredGrade = "none",
    },
}


SpaceLSCustom.Suspension = {
    {
        name = "Suspension de série",
        modIndex = -1,
        price = 0,
    },
    {
        name = "Suspension rabaissée",
        modIndex = 0,
        price = 1000,
    },
    {
        name = "Suspension de rue",
        modIndex = 1,
        price = 2000
    },
    {
        name = "Suspension de sport",
        modIndex = 2,
        price = 3000
    },
    {
        name = "Suspension de compétition",
        modIndex = 3,
        price = 5000,
    }
}

SpaceLSCustom.Transmission = {
    {
        name = "Transmission de série",
        modIndex = -1,
        price = 0,
    },
    {
        name = "Transmission de rue",
        modIndex = 0,
        price = 29500,
    },
    {
        name = "Transmission de sport",
        modIndex = 1,
        price = 32500
    },
    {
        name = "Transmission de course",
        modIndex = 2,
        price = 40000
    },
}

SpaceLSCustom.WindowTint = {
    {
        name = "Aucune",
        modIndex = -1,
        price = 0,
    },
    {
        name = "Fumé noir",
        modIndex = 1,
        price = 1500,
    },
    {
        name = "Fumé blanc",
        modIndex = 2,
        price = 1800
    },
    {
        name = "Stock",
        modIndex = 3,
        price = 2000
    },
    {
        name = "Limousine",
        modIndex = 4,
        price = 5000
    },
    {
        name = "Vert",
        modIndex = 5,
        price = 8000
    }
}